ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DDHH24:MI:SS';

--○ 게시글 정보
SELECT NVL(T.URL,'뉴비') URL, U.NICKNAME NICKNAME, TO_DATE(P.MEETDATE, 'YYYY-MM-DDHH24:MI:SS') MEETDATE,S.ADDRSINAME ADDRSINAME,A.ADDRGUNAME ADDRGUNAME, NVL(P.ADDRDETAIL,'없음') ADDRDETAIL, M.INTERMAINNAME INTERMAINNAME, I.INTERSUBNAME INTERSUBNAME, NVL(P.INTERDETAIL,'없음') INTERDETAIL, D.DRINK DRINK, G.SAMEGENDER SAMEGENDER, P.CONTENTS CONTENTS, P.MINNUM MINNUM, P.MAXNUM MAXNUM
FROM POST P LEFT JOIN USER_ESSENTIAL U
ON P.USERID = U.USERID
LEFT JOIN USER_BADGE_LOG L
ON U.BADGELOGID = L.BADGELOGID
LEFT JOIN POINT T
ON L.BADGEPOINTID = T.BADGEPOINTID
LEFT JOIN ADDR_GU A
ON P.ADDRGUID = A.ADDRGUID
LEFT JOIN ADDR_SI S
ON S.ADDRSIID = A.ADDRSIID
LEFT JOIN INTEREST_SUB I
ON P.INTERSUBID = I.INTERSUBID
LEFT JOIN INTEREST_MAIN M
ON I.INTERMAINID = M.INTERMAINID
LEFT JOIN DRINK D
ON D.DRINKID = P.DRINKID
LEFT JOIN SAME_GENDER G
ON G.SAMEGENDERID = P.SAMEGENDERID
WHERE P.POSTID = 'PT00002';

SELECT *
FROM POST_VIEW
WHERE POSTID = 'PT00002';
--○ 뷰 생성
CREATE OR REPLACE VIEW POST_VIEW
AS
SELECT P.POSTID POSTID, NVL(T.URL,'뉴비') URL, U.NICKNAME NICKNAME, TO_DATE(P.MEETDATE, 'YYYY-MM-DDHH24:MI:SS') MEETDATE,S.ADDRSINAME ADDRSINAME,A.ADDRGUNAME ADDRGUNAME, NVL(P.ADDRDETAIL,'없음') ADDRDETAIL, M.INTERMAINNAME INTERMAINNAME, I.INTERSUBNAME INTERSUBNAME, NVL(P.INTERDETAIL,'없음') INTERDETAIL, D.DRINK DRINK, G.SAMEGENDER SAMEGENDER, P.CONTENTS CONTENTS, P.MINNUM MINNUM, P.MAXNUM MAXNUM
FROM POST P LEFT JOIN USER_ESSENTIAL U
ON P.USERID = U.USERID
LEFT JOIN USER_BADGE_LOG L
ON U.BADGELOGID = L.BADGELOGID
LEFT JOIN POINT T
ON L.BADGEPOINTID = T.BADGEPOINTID
LEFT JOIN ADDR_GU A
ON P.ADDRGUID = A.ADDRGUID
LEFT JOIN ADDR_SI S
ON S.ADDRSIID = A.ADDRSIID
LEFT JOIN INTEREST_SUB I
ON P.INTERSUBID = I.INTERSUBID
LEFT JOIN INTEREST_MAIN M
ON I.INTERMAINID = M.INTERMAINID
LEFT JOIN DRINK D
ON D.DRINKID = P.DRINKID
LEFT JOIN SAME_GENDER G
ON G.SAMEGENDERID = P.SAMEGENDERID;

--○ 평점 평균
SELECT NVL(ROUND(AVG(GRADE)),1) TOTALGRADE
FROM REVIEW
WHERE TAKEUSERID = 'BLUMBALD';

--○ 인증 여부
SELECT NVL((SELECT CERTINAME FROM CERTI_VIEW WHERE USERID = 'BLUMBALD' AND CERTIID = 'CT00001'),'없음') TELCERTIID, NVL((SELECT CERTINAME FROM CERTI_VIEW WHERE USERID = 'BLUMBALD' AND CERTIID = 'CT00002'),'없음') EMAILCERTIID
FROM CERTI_VIEW
WHERE USERID = 'BLUMBALD';


SELECT *
FROM user_Essential;

SELECT *
FROM certification_cate;

CREATE OR REPLACE VIEW CERTI_VIEW
AS
SELECT C.CERTINAME, C.CERTIID, U.USERID
FROM USER_CERTIFICATION U LEFT JOIN CERTIFICATION_CATE C
ON U.CERTIID = C.CERTIID;



SELECT *
FROM CERTI_VIEW;


select *
from user_certification
WHERE USERID = 'BLUMBALD' AND CERTIID = 'CT00002';