SELECT *
FROM
(
    SELECT TITLE, CONTENTS
         , FLOOR( (ROW_NUMBER() OVER(ORDER BY NOTICEDATE DESC) - 1)/15 )+1 AS PAGENUM
         , CEIL( (FLOOR( (ROW_NUMBER() OVER(ORDER BY NOTICEDATE DESC) - 1)/15 )+1)/5 ) AS LARGEPAGENUM
    FROM NOTICE
    WHERE TITLE LIKE '%'||'°í°´'||'%'
      OR CONTENTS LIKE '%'||'°í°´'||'%'
    ORDER BY NOTICEDATE DESC
)
WHERE PAGENUM=1;

-- TotalPage, TotalLargePage¸¦ »Ì¾ÆÁÜ
SELECT CEIL(COUNT(*)/15) AS TOTALPAGE, CEIL(CEIL(COUNT(*)/15)/5) AS TOTALLARGEPAGE
FROM NOTICE;

