SELECT *
FROM
(
    SELECT M.MESSAGEID,M.CONTENTS,M.GIVEUSERID,M.TAKEUSERID,M.SENDDATE,M.CHECKDATE
             , FLOOR( (ROW_NUMBER() OVER(ORDER BY M.SENDDATE DESC) - 1)/10 )+1 AS PAGENUM
         , CEIL( (FLOOR( (ROW_NUMBER() OVER(ORDER BY M.SENDDATE DESC) - 1)/10 )+1)/5 ) AS LARGEPAGENUM
    FROM MESSAGE M LEFT JOIN DEL_MESSAGE DM  ON (M.MESSAGEID = DM.MESSAGEID AND M.TAKEUSERID=DM.USERID)
    WHERE DM.MESSAGEID IS NULL AND UPPER(TAKEUSERID)=UPPER('BROGAN')
    ORDER BY M.SENDDATE DESC
)
WHERE PAGENUM=1
;



-- TotalPage, TotalLargePage¸¦ »Ì¾ÆÁÜ
SELECT CEIL(COUNT(*)/10) AS TOTALPAGE
FROM MESSAGE M LEFT JOIN DEL_MESSAGE DM  ON (M.MESSAGEID = DM.MESSAGEID AND M.TAKEUSERID=DM.USERID)
WHERE DM.MESSAGEID IS NULL AND UPPER(TAKEUSERID)=UPPER('BROGAN')
ORDER BY M.SENDDATE DESC
;

SELECT CEIL(CEIL(COUNT(*)/10)/5) AS TOTALLARGEPAGE
FROM MESSAGE M LEFT JOIN DEL_MESSAGE DM  ON (M.MESSAGEID = DM.MESSAGEID AND M.TAKEUSERID=DM.USERID)
WHERE DM.MESSAGEID IS NULL AND UPPER(TAKEUSERID)=UPPER('BROGAN')
ORDER BY M.SENDDATE DESC
;
INSERT INTO MESSAGE(MESSAGEID, GIVEUSERID, TAKEUSERID, CONTENTS, SENDDATE, CHECKDATE) VALUES(ADD_ID('MESSAGE', 'MESSAGEID', 'MS'), 'BROGAN', 'caroin', 'º¸³½ »ç¶÷ BRGAN', SYSDATE, SYSDATE);
COMMIT;

------------------------------------------------------------------------------------------------------------------------------

SELECT *
FROM
(
    SELECT M.MESSAGEID,M.CONTENTS,M.GIVEUSERID,M.TAKEUSERID,M.SENDDATE,M.CHECKDATE
             , FLOOR( (ROW_NUMBER() OVER(ORDER BY M.SENDDATE DESC) - 1)/10 )+1 AS PAGENUM
         , CEIL( (FLOOR( (ROW_NUMBER() OVER(ORDER BY M.SENDDATE DESC) - 1)/10 )+1)/5 ) AS LARGEPAGENUM
    FROM MESSAGE M LEFT JOIN DEL_MESSAGE DM  ON (M.MESSAGEID = DM.MESSAGEID AND M.GIVEUSERID=DM.USERID)
    WHERE DM.MESSAGEID IS NULL AND UPPER(GIVEUSERID)=UPPER('BROGAN')
    ORDER BY M.SENDDATE
)
WHERE PAGENUM=1
;

-- TotalPage, TotalLargePage¸¦ »Ì¾ÆÁÜ
SELECT CEIL(COUNT(*)/10) AS TOTALPAGE
FROM MESSAGE M LEFT JOIN DEL_MESSAGE DM  ON (M.MESSAGEID = DM.MESSAGEID AND M.GIVEUSERID=DM.USERID)
WHERE DM.MESSAGEID IS NULL AND UPPER(GIVEUSERID)=UPPER('BROGAN')
ORDER BY M.SENDDATE
;

SELECT CEIL(CEIL(COUNT(*)/10)/5) AS TOTALLARGEPAGE
FROM MESSAGE M LEFT JOIN DEL_MESSAGE DM  ON (M.MESSAGEID = DM.MESSAGEID AND M.GIVEUSERID=DM.USERID)
WHERE DM.MESSAGEID IS NULL AND UPPER(GIVEUSERID)=UPPER('BROGAN')
ORDER BY M.SENDDATE
;
--------------------------------------------------------------------------------------------------------------------------------





select count(*)
from post p join interest_sub s on p.intersubid=s.intersubid
where intermainid='IM00001'
  and meetdate>=sysdate;

select *
from post_view
where postid='PT00858';

select *
from same_gender;
select *
from interest_main;

SELECT USERID, INTERSUBID AS INTERSUBID1, INTERMAINID AS INTERMAINID1, INTERSUBNAME AS INTERSUBNAME1, INTERMAINNAME AS INTERMAINNAME1
FROM
(
    SELECT UI.ID, UI.USERID, UI.INTERSUBID, "IS".INTERMAINID, "IS".INTERSUBNAME, IM.INTERMAINNAME
    FROM USER_INTEREST UI JOIN INTEREST_SUB "IS" ON UI.INTERSUBID="IS".INTERSUBID
                          JOIN INTEREST_MAIN IM ON "IS".INTERMAINID=IM.INTERMAINID
    WHERE USERID='BROGAN'
    ORDER BY UI.ID
)
WHERE ROWNUM=1	;

SELECT *
FROM
(
    SELECT UI.ID, UI.USERID, UI.INTERSUBID, "IS".INTERMAINID 
    FROM USER_INTEREST UI JOIN INTEREST_SUB "IS" ON UI.INTERSUBID="IS".INTERSUBID
    WHERE USERID='BROGAN'
    ORDER BY UI.ID
)
WHERE ROWNUM=1	;

SELECT *
FROM INTEREST_MAIN;



















--------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------







SELECT *
FROM
(
    SELECT ID, TITLE, CONTENTS, TO_CHAR(NOTICEDATE, 'YYYY-MM-DD HH24:MI') AS CSDATE
         , FLOOR( (ROW_NUMBER() OVER(ORDER BY NOTICEDATE DESC) - 1)/15 )+1 AS PAGENUM
         , CEIL( (FLOOR( (ROW_NUMBER() OVER(ORDER BY NOTICEDATE DESC) - 1)/15 )+1)/5 ) AS LARGEPAGENUM
    FROM NOTICE
    WHERE TITLE LIKE '%'||'°í°´'||'%'
      OR CONTENTS LIKE '%'||'°í°´'||'%'
    ORDER BY NOTICEDATE DESC
)
WHERE PAGENUM=1;

		SELECT COUNT(*) AS IDPWCHECK
		FROM LOGIN
		WHERE PWD = CRYPTPACK.ENCRYPT('JAVA006$','JAVA006$')
        AND USERID='BROGAN';

SELECT *
FROM
(
    SELECT ID,TITLE, CONTENTS, TO_CHAR(FAQDATE, 'YYYY-MM-DD HH24:MI') AS CSDATE
         , FLOOR( (ROW_NUMBER() OVER(ORDER BY FAQDATE DESC) - 1)/15 )+1 AS PAGENUM
         , CEIL( (FLOOR( (ROW_NUMBER() OVER(ORDER BY FAQDATE DESC) - 1)/15 )+1)/5 ) AS LARGEPAGENUM
    FROM FAQ
    WHERE TITLE LIKE '%'||'°í°´'||'%'
      OR CONTENTS LIKE '%'||'°í°´'||'%'
    ORDER BY FAQDATE DESC
)
WHERE PAGENUM=1;

-- TotalPage, TotalLargePage¸¦ »Ì¾ÆÁÜ
SELECT CEIL(COUNT(*)/15) AS TOTALPAGE
FROM NOTICE
WHERE TITLE LIKE '%'||'°í°´'||'%'
   OR CONTENTS LIKE '%'||'°í°´'||'%';

SELECT CEIL(CEIL(COUNT(*)/15)/5) AS TOTALLARGEPAGE
FROM NOTICE
WHERE TITLE LIKE '%'||'°í°´'||'%'
   OR CONTENTS LIKE '%'||'°í°´'||'%';
