---------------------------------------------------------- 노랑 ----------------------------------------------------------------


---------------------------------------------------------- 초록 ----------------------------------------------------------------
-- LOGIN(FK) 초
ALTER TABLE LOGIN
ADD CONSTRAINT LOGIN_ROLEID_FK
FOREIGN KEY(ROLEID)
REFERENCES ROLE(ROLEID);

-- ADDR_GU(FK) 초
ALTER TABLE ADDR_GU
ADD CONSTRAINT ADDR_GU_ADDRSIID
FOREIGN KEY(ADDRSIID)
REFERENCES ADDR_SI(ADDRSIID);


-- INTEREST_SUB(FK) 초
ALTER TABLE INTEREST_SUB
ADD CONSTRAINT INTEREST_SUB_INTERMAINID_FK
FOREIGN KEY(INTERMAINID)
REFERENCES INTEREST_MAIN(INTERMAINID);

-- DEL_MESSAGE(FK) 초
ALTER TABLE DEL_MESSAGE
ADD CONSTRAINT DEL_MESSAGE_MESSAGEID_FK
FOREIGN KEY(MESSAGEID)
REFERENCES MESSAGE(MESSAGEID);

ALTER TABLE DEL_MESSAGE
ADD CONSTRAINT DEL_MESSAGE_USERID_FK
FOREIGN KEY(USERID)
REFERENCES USER_ESSENTIAL(USERID);


--POINT(FK) 초
ALTER TABLE POINT
ADD CONSTRAINT POINT_BADGEPOINTCATEID_FK
FOREIGN KEY(BADGEPOINTCATEID)
REFERENCES POINT_CATE(BADGEPOINTCATEID);



---------------------------------------------------------- 파랑 ----------------------------------------------------------------

-- 외래키 제약조건 설정 

ALTER TABLE ADMIN
ADD CONSTRAINT ADMIN_USERID_FK FOREIGN KEY(USERID)
               REFERENCES LOGIN(USERID);

-- 외래키 제약조건 설정 

ALTER TABLE USER_ESSENTIAL
ADD CONSTRAINT USER_ESSENTIAL_USERID_FK FOREIGN KEY(USERID)
               REFERENCES LOGIN(USERID);
               
ALTER TABLE USER_ESSENTIAL
ADD CONSTRAINT USER_ESSENTIAL_GENDERID_FK FOREIGN KEY(GENDERID)
               REFERENCES GENDER(GENDERID);
               
ALTER TABLE USER_ESSENTIAL
ADD CONSTRAINT USER_ESSENTIAL_BADGELOGID_FK FOREIGN KEY(BADGELOGID)
               REFERENCES USER_BADGE_LOG(BADGELOGID);

---------------------------------------------------------- 보라 ----------------------------------------------------------------
ALTER TABLE DIRECT_QUESTION
ADD CONSTRAINT DIRECT_QUESTION_USERID_FK FOREIGN KEY(USERID)
               REFERENCES USER_ESSENTIAL(USERID);

ALTER TABLE USER_ADDR
ADD CONSTRAINT USER_ADDR_USERID_FK FOREIGN KEY(USERID)
               REFERENCES USER_ESSENTIAL(USERID);

ALTER TABLE USER_ADDR
ADD CONSTRAINT USER_ADDR_ADDRGUID_FK FOREIGN KEY(ADDRGUID)
               REFERENCES ADDR_GU(ADDRGUID);

-- 외래키 제약조건 설정 
ALTER TABLE USER_SUB
ADD CONSTRAINT USERSUB_USERID_FK FOREIGN KEY(USERID)
               REFERENCES USER_ESSENTIAL(USERID);


-- 외래키 제약조건 설정 
ALTER TABLE DEL_USER
ADD CONSTRAINT DEL_USER_USERID_FK FOREIGN KEY(USERID)
               REFERENCES USER_ESSENTIAL(USERID);


-- 외래키 제약조건 설정 
ALTER TABLE FOLLOW
ADD CONSTRAINT FOLLOW_GIVEUSERID_FK FOREIGN KEY(GIVEUSERID)
               REFERENCES USER_ESSENTIAL(USERID);

ALTER TABLE FOLLOW
ADD CONSTRAINT FOLLOW_TAKEUSERID_FK FOREIGN KEY(TAKEUSERID)
               REFERENCES USER_ESSENTIAL(USERID);


-- 외래키 제약조건 설정 
ALTER TABLE USER_INTEREST
ADD CONSTRAINT USER_INTEREST_USERID_FK FOREIGN KEY(USERID)
               REFERENCES USER_ESSENTIAL(USERID);

ALTER TABLE USER_INTEREST
ADD CONSTRAINT USER_INTEREST_INTERNAME_FK FOREIGN KEY(INTERNAME)
               REFERENCES INTEREST_SUB(INTERSUBID);

-- 외래키 제약조건 설정 
ALTER TABLE USER_CERTIFICATION
ADD CONSTRAINT USER_CERTIFICATION_USERID_FK FOREIGN KEY(USERID)
               REFERENCES USER_ESSENTIAL(USERID);


-- 외래키 제약조건 설정 
ALTER TABLE MESSAGE
ADD CONSTRAINT MESSAGE_GIVEUSERID_FK FOREIGN KEY(GIVEUSERID)
               REFERENCES LOGIN(USERID);
ALTER TABLE MESSAGE
ADD CONSTRAINT MESSAGE_TAKEUSERID_FK FOREIGN KEY(TAKEUSERID)
               REFERENCES USER_ESSENTIAL(USERID);

-- 외래키 제약조건 설정 
ALTER TABLE POST
ADD CONSTRAINT POST_USERID_FK FOREIGN KEY(USERID)
               REFERENCES USER_ESSENTIAL(USERID);
               
               
ALTER TABLE POST
ADD CONSTRAINT POST_ADDRGUID_FK FOREIGN KEY(ADDRGUID)
               REFERENCES ADDR_GU(ADDRGUID);

ALTER TABLE POST
ADD CONSTRAINT POST_INTERESTSUBID_FK FOREIGN KEY(INTERESTSUBID)
               REFERENCES INTEREST_SUB(INTERSUBID);

ALTER TABLE POST
ADD CONSTRAINT POST_MOODID_FK FOREIGN KEY(MOODID)
               REFERENCES MOOD(MOODID);
               
ALTER TABLE POST
ADD CONSTRAINT POST_DRINKID_FK FOREIGN KEY(DRINKID)
               REFERENCES DRINK(DRINKID);

ALTER TABLE POST
ADD CONSTRAINT POST_SAMEGENDERID_FK FOREIGN KEY(SAMEGENDERID)
               REFERENCES SAME_GENDER(SAMEGENDERID);


---------------------------------------------------------- 주황 ----------------------------------------------------------------

-- DEL_POST(FK) 주
ALTER TABLE DEL_POST
ADD CONSTRAINT DEL_POST_POSTID_FK
FOREIGN KEY(POSTID)
REFERENCES POST(POSTID);

--REPORT_POST(FK) 주
ALTER TABLE REPORT_POST
ADD CONSTRAINT REPORT_POST_POSTID_FK
FOREIGN KEY(POSTID)
REFERENCES POST(POSTID);

ALTER TABLE REPORT_POST
ADD CONSTRAINT REPORT_POST_USERID_FK
FOREIGN KEY(USERID)
REFERENCES USER_ESSENTIAL(USERID);

ALTER TABLE REPORT_POST
ADD CONSTRAINT REPORT_POST_REPORTCATEID_FK
FOREIGN KEY(REPORTCATEID)
REFERENCES REPORT_CATE(REPORTCATEID);

--JOIN(FK) 주
ALTER TABLE JOIN
ADD CONSTRAINT JOIN_POSTID_FK
FOREIGN KEY(POSTID)
REFERENCES POST(POSTID);

ALTER TABLE JOIN
ADD CONSTRAINT JOIN_USERID_FK
FOREIGN KEY(USERID)
REFERENCES USER_ESSENTIAL(USERID);

ALTER TABLE JOIN
ADD CONSTRAINT JOIN_STATUSID_FK
FOREIGN KEY(STATUSID)
REFERENCES STATUS(STATUSID);


--REVIEW 주
ALTER TABLE REVIEW
ADD CONSTRAINT REVIEW_POSTID_FK
FOREIGN KEY(POSTID)
REFERENCES POST(POSTID);

ALTER TABLE REVIEW
ADD CONSTRAINT REVIEW_GIVEUSERID_FK
FOREIGN KEY(TAKEUSERID)
REFERENCES USER_ESSENTIAL(USERID);

ALTER TABLE REVIEW
ADD CONSTRAINT REVIEW_TAKEUSERID_FK
FOREIGN KEY(GIVEUSERID)
REFERENCES USER_ESSENTIAL(USERID);



---------------------------------------------------------- 분홍 ----------------------------------------------------------------

--○ DEL_JOIN 구간
ALTER TABLE DEL_JOIN ADD CONSTRAINT DEL_JOIN_JOINID_FK FOREIGN KEY(JOINID) REFERENCES JOIN(JOINID);

--○ REPORT_JOIN 구간
ALTER TABLE REPORT_JOIN ADD CONSTRAINT REPORT_JOIN_JOINID_FK FOREIGN KEY(JOINID) REFERENCES JOIN(JOINID);

ALTER TABLE REPORT_JOIN ADD CONSTRAINT REPORT_JOIN_USERID_FK FOREIGN KEY(USERID) REFERENCES USER_ESSENTIAL(USERID);

ALTER TABLE REPORT_JOIN ADD CONSTRAINT REPORT_JOIN_REPORTCATEID_FK FOREIGN KEY(REPORTCATEID) REFERENCES REPORT_CATE(REPORTCATEID);


--○ REPLY 구간
ALTER TABLE REPLY ADD CONSTRAINT REPLY_JOINID_FK FOREIGN KEY(JOINID) REFERENCES JOIN(JOINID);

ALTER TABLE REPLY ADD CONSTRAINT REPLY_USERTYPEID FOREIGN KEY(USERTYPEID) REFERENCES REPLY_USER_TYPE(USERTYPEID);

ALTER TABLE REPORT_REPLY ADD CONSTRAINT REPORT_REPLY_UESRID_FK FOREIGN KEY(UESRID) REFERENCES USER_ESSENTIAL(USERID);

ALTER TABLE REPORT_REPLY ADD CONSTRAINT REPORT_REPLY_REPORTCATEID_FK FOREIGN KEY(REPORTCATEID) REFERENCES REPORT_CATE(REPORTCATEID);

--○ REVIEW_SUB 구간
ALTER TABLE REVIEW_SUB ADD CONSTRAINT REVIEW_SUB_REVIEWID_FK FOREIGN KEY(REVIEWID) REFERENCES REVIEW(REVIEWID);

ALTER TABLE REVIEW_SUB ADD CONSTRAINT REVIEW_SUB_BADGEPOINTID_FK FOREIGN KEY(BADGEPOINTID) REFERENCES POINT(BADGEPOINTID);

--○ USER_BADGE_LOG 구간
ALTER TABLE USER_BADGE_LOG ADD CONSTRAINT USER_BADGE_LOG_BADGEPOINTID_FK FOREIGN KEY(BADGEPOINTID) REFERENCES POINT(BADGEPOINTID);

ALTER TABLE USER_BADGE_LOG ADD CONSTRAINT USER_BADGE_LOG_EXPIRATIONID_FK FOREIGN KEY(EXPIRATIONREVIEWID) REFERENCES REVIEW(REVIEWID);

---------------------------------------------------------- 빨강 ----------------------------------------------------------------

--○ DEL_REPLY 구간
ALTER TABLE DEL_REPLY ADD CONSTRAINT DEL_REPLY_REPLYID_FK FOREIGN KEY(REPLYID) REFERENCES REPLY(REPLYID);

--○ REPORT_REPLY 구간
ALTER TABLE REPORT_REPLY ADD CONSTRAINT REPORT_REPLY_REPLYID_FK FOREIGN KEY(REPLYID) REFERENCES REPLY(REPLYID);

