-- ID 자동 추가 함수
-- 사용 예시
-- ADD_ID('테이블명', 'ID컬럼명', '접두사')
-- INSERT INTO ADDR_GU(ADDRGUID, ADDRGUNAME) VALUES(ADD_ID('ADDR_GU', 'ADDRGUID', 'GU'), '구이름');
CREATE OR REPLACE FUNCTION ADD_ID
( TABLE_NAME        IN VARCHAR2
, ID_COLUMN IN VARCHAR2
, ID_SUFFIX IN VARCHAR2
)
RETURN VARCHAR2
IS
    V_RESULT    VARCHAR2(10);
    V_SQL       VARCHAR2(1000);
    V_SUFFIX    VARCHAR2(10);
BEGIN
    V_SUFFIX := ID_SUFFIX;
    V_SQL := 'SELECT ''' || V_SUFFIX || ''' || LPAD( TO_CHAR(NVL(MAX(TO_NUMBER(SUBSTR('|| ID_COLUMN ||', 3))), 0) + 1), 5, ''0'') FROM ' || TABLE_NAME ;

    EXECUTE IMMEDIATE V_SQL INTO V_RESULT;

    RETURN V_RESULT;
END;


